# Plotting topologies generated by TWISST
### Parsing through topologies with certain features (e.g., a monophyletic luciae and virginiae) so that their support values
### can be lumped together and the overall support for these features (and not just individual topologies) 
### can be plotted across the genome 

setwd("/Users/aririce/Desktop/PhD Thesis/Projects/Leiothlypis/Leiothlypis analyses/Ch1_new/Genomic_architecture")
library(ape)
library(phytools)
library(dplyr)

tree_table <- read.table("Leio_trees.tsv", header = FALSE, stringsAsFactors = FALSE)
colnames(tree_table) <- c("name", "tree_in_newick_format")
Leiotrees <- "Leio_trees.tsv"
all_trees <- ape::read.tree(Leiotrees)

VL_monophyly <- list()
VR_monophyly <- list()
VC_monophyly <- list()
ruficapilla_eyeringed_outgroup <- list()
crissalis_eyeringed_outgroup <- list()
peregrina_outgroup <- list()
eye_ringed_monophyly <- list()

for (i in 1:length(all_trees)) {
  topo_rep <- all_trees[[i]]
  VL_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "luciae"))
  VL_monophyly <- append(VL_monophyly, VL_rep)
}

for (j in 1:length(all_trees)) {
  topo_rep <- all_trees[[j]]
  VR_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "ruficapilla"))
  VR_monophyly <- append(VR_monophyly, VR_rep)
}
  
for (k in 1:length(all_trees)) {
  topo_rep <- all_trees[[k]]
  VC_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "crissalis"))
  VC_monophyly <- append(VC_monophyly, VC_rep)
}

for (a in 1:length(all_trees)) {
  topo_rep <- all_trees[[a]]
  western_mono_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "crissalis", "luciae"))
  ruficapilla_eyeringed_outgroup <- append(ruficapilla_eyeringed_outgroup, western_mono_rep)
}

for (b in 1:length(all_trees)) {
  topo_rep <- all_trees[[b]]
  western_para_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "luciae", "ruficapilla"))
  crissalis_eyeringed_outgroup <- append(crissalis_eyeringed_outgroup, western_para_rep)
}

for (c in 1:length(all_trees)) {
  topo_rep <- all_trees[[c]]
  peregrina_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "crissalis", "celata", "luciae", "ruficapilla"))
  peregrina_outgroup <- append(peregrina_outgroup, peregrina_rep)
}

for (d in 1:length(all_trees)) {
  topo_rep <- all_trees[[d]]
  eyeringed_rep <- is.monophyletic(phy = topo_rep, tips = c("virginiae", "crissalis", "luciae", "ruficapilla"))
  eye_ringed_monophyly <- append(eye_ringed_monophyly, eyeringed_rep)
}

VL_monophyly <- unlist(VL_monophyly) %>% as.data.frame() %>% `colnames<-`(c("VL_monophyly"))
VR_monophyly <- unlist(VR_monophyly) %>% as.data.frame() %>% `colnames<-`(c("VR_monophyly"))
VC_monophyly <- unlist(VC_monophyly) %>% as.data.frame() %>% `colnames<-`(c("VC_monophyly"))
ruficapilla_eyeringed_outgroup <- unlist(ruficapilla_eyeringed_outgroup) %>% as.data.frame() %>% `colnames<-`(c("ruficapilla_eyeringed_outgroup"))
crissalis_eyeringed_outgroup <- unlist(crissalis_eyeringed_outgroup) %>% as.data.frame() %>% `colnames<-`(c("crissalis_eyeringed_outgroup"))
peregrina_outgroup <- unlist(peregrina_outgroup) %>% as.data.frame() %>% `colnames<-`(c("peregrina_outgroup"))
eye_ringed_monophyly <- unlist(eye_ringed_monophyly) %>% as.data.frame() %>% `colnames<-`(c("eye_ringed_monophyly"))

tree_table_cat <- cbind(tree_table, VL_monophyly, VR_monophyly, VC_monophyly, ruficapilla_eyeringed_outgroup, crissalis_eyeringed_outgroup, peregrina_outgroup, eye_ringed_monophyly)

# Subsetting
VL_topos <- subset(tree_table_cat, VL_monophyly=='TRUE', select = c(1,2))
VR_topos <- subset(tree_table_cat, VR_monophyly=='TRUE', select = c(1,2))
VC_topos <- subset(tree_table_cat, VC_monophyly=='TRUE', select = c(1,2))
ruf_out_topos <- subset(tree_table_cat, ruficapilla_eyeringed_outgroup=='TRUE', select = c(1,2))
cri_out_topos <-subset(tree_table_cat, crissalis_eyeringed_outgroup=='TRUE', select = c(1,2))
pere_out_topos <-subset(tree_table_cat, peregrina_outgroup=='TRUE', select = c(1,2))
eye_ring_topos <- subset(tree_table_cat, eye_ringed_monophyly=='TRUE', select = c(1,2))

# Now subset the original tree weights file by topologies with these features
xx <- read.table("Leiothlypis_50kbp.trees.weights.tsv", header = TRUE, stringsAsFactors = FALSE)
# Import the metadata file w/ chrom #s and start and end points for each window. 
xxdata <- read.table("Leiothlypis_50kbp_data", header = TRUE, stringsAsFactors=F)
# Combine the metadata file with the actual data. 
all_xx_info <- cbind(xxdata, xx)
# Rearrange by chromosome #, then start point (Note that the Z chromosome is #33)
all_xx_info_arranged <- all_xx_info %>% arrange(chrom, start)

#################################################
# Generate a table of topology support for a monophyletic eyeringed clade 
#################################################
names.use <- setNames(data.frame(t(eye_ring_topos[,-1])), eye_ring_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
eye_ring_subset <- all_xx_info_arranged[, names.use]
eye_ring_support <- as.data.frame(rowSums(eye_ring_subset)/78125)
eye_ring_support$new_column <- (1 - eye_ring_support$`rowSums(eye_ring_subset)/78125`)
colnames(eye_ring_support) <- c("Monophyletic_eye_ringed_clade", "Non-monophyletic_eye_ringed_clade")
final_eye_ringed <- cbind(all_xx_info_arranged[,1:3], eye_ring_support)

#################################################
# Generate a table of topology support for a monophyletic crowned clade w/ peregrina as outgroup
#################################################
names.use <- setNames(data.frame(t(pere_out_topos[,-1])), pere_out_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
Pere_out_subset <- all_xx_info_arranged[, names.use]
Pere_out_support <- as.data.frame(rowSums(Pere_out_subset)/78125)
Pere_out_support$new_column <- (1 - Pere_out_support$`rowSums(Pere_out_subset)/78125`)
colnames(Pere_out_support) <- c("Monophyletic_crowned_clade", "Non-monophyletic_crowned_clade")
final_crowned <- cbind(all_xx_info_arranged[,1:3], Pere_out_support)

#################################################
# Generate a table of topology support for VLR and VLCr clades
#################################################
names.use <- setNames(data.frame(t(cri_out_topos[,-1])), cri_out_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
Cri_out_subset <- all_xx_info_arranged[, names.use]
Cri_out_support <- as.data.frame(rowSums(Cri_out_subset)/78125)
names.use <- setNames(data.frame(t(ruf_out_topos[,-1])), ruf_out_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
Ruf_out_subset <- all_xx_info_arranged[, names.use]
Ruf_out_support <- as.data.frame(rowSums(Ruf_out_subset)/78125)
final_VLCr_VLR <- cbind(all_xx_info_arranged[,1:3], Ruf_out_support, Cri_out_support)
final_VLCr_VLR$new_column <- 1 - (final_VLCr_VLR$`rowSums(Ruf_out_subset)/78125` + final_VLCr_VLR$`rowSums(Cri_out_subset)/78125`)
colnames(final_VLCr_VLR) <- c("chrom", "start", "end", "Monophyletic_VLCr", "Monophyletic_VLR", "other_topologies_VLCrR")

#################################################
# Generate a table of topology support for different sister taxa w/ virginiae
#################################################
names.use <- setNames(data.frame(t(VL_topos[,-1])), VL_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
VL_subset <- all_xx_info_arranged[, names.use]
VL_support <- as.data.frame(rowSums(VL_subset)/78125)
names.use <- setNames(data.frame(t(VR_topos[,-1])), VR_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
VR_subset <- all_xx_info_arranged[, names.use]
VR_support <- as.data.frame(rowSums(VR_subset)/78125)
names.use <- setNames(data.frame(t(VC_topos[,-1])), VC_topos[,1])
names.use <- names(names.use)[!(names(names.use) %in% all_xx_info_arranged)]
VC_subset <- all_xx_info_arranged[, names.use]
VC_support <- as.data.frame(rowSums(VC_subset)/78125)
final_V_sister <- cbind(all_xx_info_arranged[,1:3], VL_support, VR_support, VC_support)
final_V_sister$new_column <- 1 - (final_V_sister$`rowSums(VL_subset)/78125` + final_V_sister$`rowSums(VR_subset)/78125` + final_V_sister$`rowSums(VC_subset)/78125`)
colnames(final_V_sister) <- c("chrom", "start", "end", "Monophyletic_VL", "Monophyletic_VR", "Monophyletic_VCr", "other_topologies_V_sister")

##### Export everything as one big table so I can put it into the other big table w/ the genomic architecture ########

merged_topology_data <- cbind(final_crowned, final_eye_ringed[,4:5], final_VLCr_VLR[,4:6], final_V_sister[4:7])
write.table(merged_topology_data, file="merged_topology_stuff.tsv", quote=F, row.names=F, col.names=T, sep = "\t")
            
########## Prepare the data for plotting ##################
library(tidyverse)
Crowned_plot <- final_crowned
Eye_ringed_plot <- final_eye_ringed

# Make a new empty dataframe that'll provide genome-wide positions of each window 
# instead of positions within each chromosome
new_chrom_pos <- Crowned_plot[,1:3]
colnames(new_chrom_pos) <- c("chrom", "genom_start", "genom_end")
new_chrom_pos <- new_chrom_pos[FALSE,]

# Make a list of all the sizes for each chromosome
chroms <- unique(Crowned_plot$chrom)
chroms[[31]] <- 31
chroms<-append(chroms, 32:33, after = length(chroms))
chrom_sizes <- list()
for (w in 1:length(chroms)) {
  w_rep <- subset(Crowned_plot, chrom==w, select = c(1:3))
  w_rep_chrom_end <- w_rep[nrow(w_rep),3] %>% as.list()
  chrom_sizes <- append(chrom_sizes, w_rep_chrom_end)
}
chrom_sizes <- unlist(chrom_sizes) %>% as.data.frame() %>% `colnames<-`(c("chrom_size")) %>% `rownames<-` (c(NULL))

# Now make a new dataframe with 0 in the first cell. 
cumulative_chrom_size <- as.data.frame(0) %>% `colnames<-`(c("numbers_to_add"))

# Now do two more loops
# The 30 in the x loop is just the # of chromosomes minus 1. 
# Change if using this with different organisms/ genomes.  
for (x in 1:30) {
  x_rep <- chrom_sizes[x,1] + cumulative_chrom_size[x,1] %>% as.data.frame() %>% `colnames<-`(c("numbers_to_add"))
  cumulative_chrom_size <- rbind(cumulative_chrom_size, x_rep)
}
for (y in 1:30) {
  y_rep <- subset(Crowned_plot, chrom==y, select = c(1:3))
  y_rep$genom_start <- (y_rep$start) + (cumulative_chrom_size[y,1])
  y_rep$genom_end <- (y_rep$end) + (cumulative_chrom_size[y,1])
  y_rep <- subset(y_rep, select = c(1,4,5))
  new_chrom_pos <- rbind(new_chrom_pos, y_rep)
}

# Now add values for chrom 33 manually (because 31 and 32 were skipped)
chrom33_pos <- subset(Crowned_plot, chrom=='33', select = c(1:3))
chrom33_pos$genom_start <- (chrom33_pos$start) + (new_chrom_pos[nrow(new_chrom_pos),3])
chrom33_pos$genom_end <- (chrom33_pos$end) + (new_chrom_pos[nrow(new_chrom_pos),3])
chrom33_pos <- subset(chrom33_pos, select = c(1,4,5))

new_chrom_pos <- rbind(new_chrom_pos, chrom33_pos)
Crowned_plot <- cbind(Crowned_plot, new_chrom_pos[,2:3])
Eye_ringed_plot <- cbind(Eye_ringed_plot, new_chrom_pos[,2:3])

# Clean up the workspace
rm(list = ls()[grep("support", ls())])
rm(list = ls()[grep("topos", ls())])
rm(list = ls()[grep("subset", ls())])
rm(list = ls()[grep("support", ls())])
rm(list = ls()[grep("monophyly", ls())])
rm(list = ls()[grep("tree", ls())])
rm(list = ls()[grep("rep", ls())])
rm(list = ls()[grep("xx", ls())])
rm(list = ls()[grep("outgroup", ls())])


######################################################
######### Actual plotting ############################
######################################################
######## Make the windows larger so the plot looks nice ##########
###### Plot # 1 ##################################################
Crowned_plot_big_windows <- Crowned_plot[FALSE,]
window_size <- 100
# 20 windows that are 50 kbp each = 1 Mbp (so if we make the windows 1 megabase instead of 50 kbp, there are 1024 of them)
Crowned_plot$window_group = (1:nrow(Crowned_plot) - 1) %/% window_size

# Run this simple equation to find the number of reps appropriate for the number of windows
# (20474*50000) / (window_size*50000)
for (z in 0:204) {
  z_rep <- subset(Crowned_plot, window_group==z)
  z_rep_average1 <- mean(z_rep$Monophyletic_crowned_clade)
  z_rep_average2 <- mean(z_rep$`Non-monophyletic_crowned_clade`)
  z_rep_genom_start <- z_rep[1,6]
  z_rep_genom_end <- z_rep[nrow(z_rep), 7]
  z_rep[nrow(z_rep) + 1,] = c("NA", "NA", "NA", z_rep_average1, z_rep_average2, z_rep_genom_start, z_rep_genom_end, z)
  new_z_rep <- z_rep[nrow(z_rep),]
  Crowned_plot_big_windows <- rbind(Crowned_plot_big_windows, new_z_rep)
}

Crowned_plot_big_windows <- Crowned_plot_big_windows[,4:8]
Crowned_plot_big_windows[, 1:5] <- sapply(Crowned_plot_big_windows[, 1:5], as.numeric)

# Rename the columns so that the dominant topology is plotted on the bottom (ggplot does it in alphabetical order)
colnames(Crowned_plot_big_windows) <- c("b_Monophyletic_crowned_clade", "a_Non-monophyletic_crowned_clade", 
                                         "genom_start", "genom_end", "window_group")

Plot_1 <- Crowned_plot_big_windows %>% 
  mutate(genom_start) %>% 
  gather(variable, value, b_Monophyletic_crowned_clade:`a_Non-monophyletic_crowned_clade`) %>% 
  ggplot(aes(x = genom_start, y = value, fill = variable)) + geom_area() + scale_fill_manual(values = c("#CD5C5C","#FFA500")) +
  scale_y_continuous(name = element_blank(), expand = c(0,0), breaks = c(0.0,0.5,1.0)) +
  scale_x_continuous(name = element_blank(), breaks = c(cumulative_chrom_size$numbers_to_add), 
                     expand = c(0, 0)) + theme(axis.text.x = element_blank(), axis.ticks.length = unit(1.5, "mm"), 
                                               axis.ticks=element_line(size=0.5, color="#666666"), plot.margin = unit(c(1,0,1,0), "lines"),
                                               axis.text.y = element_text(size = 8), legend.text = element_blank())

###### Plot # 1.5 #################################################
Eye_ringed_plot_big_windows <- Eye_ringed_plot[FALSE,]
window_size <- 100
# 20 windows that are 50 kbp each = 1 Mbp (so if we make the windows 1 megabase instead of 50 kbp, there are 1024 of them)
Eye_ringed_plot$window_group = (1:nrow(Eye_ringed_plot) - 1) %/% window_size

# Run this simple equation to find the number of reps appropriate for the number of windows
# (20474*50000) / (window_size*50000)
for (z in 0:204) {
  z_rep <- subset(Eye_ringed_plot, window_group==z)
  z_rep_average1 <- mean(z_rep$Monophyletic_eye_ringed_clade)
  z_rep_average2 <- mean(z_rep$`Non-monophyletic_eye_ringed_clade`)
  z_rep_genom_start <- z_rep[1,6]
  z_rep_genom_end <- z_rep[nrow(z_rep), 7]
  z_rep[nrow(z_rep) + 1,] = c("NA", "NA", "NA", z_rep_average1, z_rep_average2, z_rep_genom_start, z_rep_genom_end, z)
  new_z_rep <- z_rep[nrow(z_rep),]
  Eye_ringed_plot_big_windows <- rbind(Eye_ringed_plot_big_windows, new_z_rep)
}

Eye_ringed_plot_big_windows <- Eye_ringed_plot_big_windows[,4:8]
Eye_ringed_plot_big_windows[, 1:5] <- sapply(Eye_ringed_plot_big_windows[, 1:5], as.numeric)

# Rename the columns so that the dominant topology is plotted on the bottom (ggplot does it in alphabetical order)
colnames(Eye_ringed_plot_big_windows) <- c("b_Monophyletic_eye_ringed_clade", "a_Non-monophyletic_eye_ringed_clade", 
                                        "genom_start", "genom_end", "window_group")

Plot_1.5 <- Eye_ringed_plot_big_windows %>% 
  mutate(genom_start) %>% 
  gather(variable, value, b_Monophyletic_eye_ringed_clade:`a_Non-monophyletic_eye_ringed_clade`) %>% 
  ggplot(aes(x = genom_start, y = value, fill = variable)) + geom_area() + scale_fill_manual(values = c("#228B22", "#7de33d")) + #c("#2E8B57", "#66CDAA"))
  scale_y_continuous(name = element_blank(), expand = c(0,0), breaks = c(0.0,0.5,1.0)) +
  scale_x_continuous(name = element_blank(), breaks = c(cumulative_chrom_size$numbers_to_add), 
                     expand = c(0, 0)) + theme(axis.text.x = element_blank(), axis.ticks.length = unit(1.5, "mm"), 
                                               axis.ticks=element_line(size=0.5, color="#666666"), plot.margin = unit(c(1,0,1,0), "lines"),
                                               axis.text.y = element_text(size = 8), legend.text = element_blank())


###### Plot # 2 ##################################################
VLCr_VLR_plot <- final_VLCr_VLR
VLCr_VLR_plot <- cbind(VLCr_VLR_plot, new_chrom_pos[,2:3])

VLCr_VLR_plot_big_windows <- VLCr_VLR_plot[FALSE,]
window_size <- 100
# 20 windows that are 50 kbp each = 1 Mbp (so if we make the windows 1 megabase instead of 50 kbp, there are 1024 of them)
VLCr_VLR_plot$window_group = (1:nrow(VLCr_VLR_plot) - 1) %/% window_size

# Run this simple equation to find the number of reps appropriate for the number of windows
# (20474*50000) / (window_size*50000)
for (z in 0:204) {
  z_rep <- subset(VLCr_VLR_plot, window_group==z)
  z_rep_average1 <- mean(z_rep$Monophyletic_VLCr)
  z_rep_average2 <- mean(z_rep$Monophyletic_VLR)
  z_rep_average3 <- mean(z_rep$other_topologies_VLCrR)
  z_rep_genom_start <- z_rep[1,7]
  z_rep_genom_end <- z_rep[nrow(z_rep), 8]
  z_rep[nrow(z_rep) + 1,] = c("NA", "NA", "NA", z_rep_average1, z_rep_average2, z_rep_average3, z_rep_genom_start, z_rep_genom_end, z)
  new_z_rep <- z_rep[nrow(z_rep),]
  VLCr_VLR_plot_big_windows <- rbind(VLCr_VLR_plot_big_windows, new_z_rep)
}

VLCr_VLR_plot_big_windows <- VLCr_VLR_plot_big_windows[,4:9]
VLCr_VLR_plot_big_windows[, 1:6] <- sapply(VLCr_VLR_plot_big_windows[, 1:6], as.numeric)

# Rename the columns so that the dominant topology is plotted on the bottom (ggplot does it in alphabetical order)
colnames(VLCr_VLR_plot_big_windows) <- c("c_monophyletic_VLCr", "b_monophyletic_VLR", 
                                         "a_other_topologies_VLCrR", "genom_start", 
                                         "genom_end", "window_group")

Plot_2 <- VLCr_VLR_plot_big_windows %>% 
  mutate(genom_start) %>% 
  gather(variable, value, c_monophyletic_VLCr:a_other_topologies_VLCrR) %>% 
  ggplot(aes(x = genom_start, y = value, fill = variable)) + geom_area() + scale_fill_manual(values=c("#4169E1", "#00b2ff", "#77f2ff")) +
  scale_y_continuous(name = element_blank(), expand = c(0,0), breaks = c(0.0,0.5,1.0)) +
  scale_x_continuous(name = element_blank(), breaks = c(cumulative_chrom_size$numbers_to_add), 
                     expand = c(0, 0)) + theme(axis.text.x = element_blank(), axis.ticks.length = unit(1.5, "mm"), 
                                               axis.ticks=element_line(size=0.5, color="#666666"), plot.margin = unit(c(1,0,1,0), "lines"),
                                               axis.text.y = element_text(size = 8), legend.text = element_blank())

###### Plot # 3 ###################################################
V_sister_plot <- final_V_sister
V_sister_plot <- cbind(V_sister_plot, new_chrom_pos[,2:3])

V_sister_plot_big_windows <- V_sister_plot[FALSE,]
window_size <- 100
# 20 windows that are 50 kbp each = 1 Mbp (so if we make the windows 1 megabase instead of 50 kbp, there are 1024 of them)
V_sister_plot$window_group = (1:nrow(V_sister_plot) - 1) %/% window_size

# Run this simple equation to find the number of reps appropriate for the number of windows
# (20474*50000) / (window_size*50000)
for (z in 0:204) {
  z_rep <- subset(V_sister_plot, window_group==z)
  z_rep_average1 <- mean(z_rep$Monophyletic_VL)
  z_rep_average2 <- mean(z_rep$Monophyletic_VR)
  z_rep_average3 <- mean(z_rep$Monophyletic_VCr)
  z_rep_average4 <- mean(z_rep$other_topologies_V_sister)
  z_rep_genom_start <- z_rep[1,8]
  z_rep_genom_end <- z_rep[nrow(z_rep), 9]
  z_rep[nrow(z_rep) + 1,] = c("NA", "NA", "NA", z_rep_average1, z_rep_average2, z_rep_average3, z_rep_average4, z_rep_genom_start, z_rep_genom_end, z)
  new_z_rep <- z_rep[nrow(z_rep),]
  V_sister_plot_big_windows <- rbind(V_sister_plot_big_windows, new_z_rep)
}

V_sister_plot_big_windows <- V_sister_plot_big_windows[,4:10]
V_sister_plot_big_windows[, 1:7] <- sapply(V_sister_plot_big_windows[, 1:7], as.numeric)

# Rename the columns so that the dominant topology is plotted on the bottom (ggplot does it in alphabetical order)
colnames(V_sister_plot_big_windows) <- c("d_Monophyletic_VL", "b_Monophyletic_VR", "c_Monophyletic_VCr", "a_other_topologies_V_sister", 
                                        "genom_start", "genom_end", "window_group")

Plot_3 <- V_sister_plot_big_windows %>% 
  mutate(genom_start) %>% 
  gather(variable, value, d_Monophyletic_VL:a_other_topologies_V_sister) %>% 
  ggplot(aes(x = genom_start, y = value, fill = variable)) + geom_area() + scale_fill_manual(values=c("#CD5C5C","#FF6347", "#FFA500", "#FFD700")) +
  scale_y_continuous(name = element_blank(), expand = c(0,0), breaks = c(0.0,0.5,1.0)) +
  scale_x_continuous(name = element_blank(), breaks = c(cumulative_chrom_size$numbers_to_add), 
                     expand = c(0, 0)) + theme(axis.text.x = element_blank(), axis.ticks.length = unit(1.5, "mm"), 
                                               axis.ticks=element_line(size=0.5, color="#666666"), plot.margin = unit(c(1,0,1,0), "lines"),
                                               axis.text.y = element_text(size = 8), legend.text = element_blank())

##################
library(cowplot)
plot_grid(Plot_1.5, Plot_2, Plot_3, labels = c('A','B','C'), label_size = 12, ncol = 1, vjust = 1.25, hjust = -2.5) + 
  theme(plot.margin = unit(c(0.5,0,0,0), "cm"))

#################################################

# Chromosome-level stats
chrom_average_topo_support <- c()
options(scipen = 999)

for (i in 1:33) {
  chrom_rep <- subset(merged_topology_data, chrom == i, select = c(1,4:14))
  chrom_means_rep <- colMeans(chrom_rep) %>% as.table(,row.names = FALSE)
  chrom_average_topo_support <- rbind(chrom_means_rep, chrom_average_topo_support)
}
chrom_average_topo_support <- na.omit(chrom_average_topo_support) %>% as.data.frame()

chrom_average_topo_support <- chrom_average_topo_support %>% arrange(chrom) %>% cbind(chrom_sizes)
chrom_average_topo_support$log_chrom_size <- log(chrom_average_topo_support$chrom_size)

final_chrom_average_topo_support <- chrom_average_topo_support %>%
  tidyr::gather(key = supported_topology, value = weighting, -chrom, -chrom_size, -log_chrom_size)

# Remove rows with stats that tell the same story

final_chrom_average_topo_support <- subset(final_chrom_average_topo_support, supported_topology != 'Non-monophyletic_crowned_clade' & 
                                             supported_topology != 'Non-monophyletic_eye_ringed_clade' &
                                             supported_topology != 'Monophyletic_VLR' & 
                                             supported_topology != 'other_topologies_VLCrR' &  
                                             supported_topology != 'other_topologies_V_sister' &
                                             supported_topology != 'Monophyletic_VR' &
                                             supported_topology != 'Monophyletic_VCr')

library(ggpubr)

Topology_plot <- ggplot(data = final_chrom_average_topo_support, aes(x=log_chrom_size, y=weighting, color=supported_topology)) + 
  geom_point(alpha = 0.5, size = 2) + scale_x_continuous(expand = c(0, 0), limits = c(14,19.05)) + scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) + 
  theme(plot.background = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=1),
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14)) + 
  geom_smooth(method = "lm", se = FALSE, fullrange = TRUE, size= 0.5) + 
  stat_cor(aes(label = after_stat(rr.label)), geom = "label", label.x = Inf, hjust = 4)
Topology_plot + labs(x = "log Chromosome size (bp)", y = "Weighting") + 
  theme(legend.position = "none") + scale_colour_manual(values = c("#0D0887FF","#B12A90FF", "#E16462FF", "#e29538"))


